---
- hosts: gluster
  sudo: True
  vars:
    gluster_brick_dir: /server/gluster/brick
    gluster_mount_dir: /mnt/gluster
    gluster_brick_name: gluster

  tasks:
    - name: Create mount directory
      file: "path={{ item }} state=directory mode=0775"
      with_items:
        - "{{ gluster_brick_dir }}"
        - "{{ gluster_mount_dir }}"

    - name: Create gluster volume
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        bricks: "{{ gluster_brick_dir }}"
        replicas: 2
        cluster: "{{ groups.gluster | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true

    - name: Check gluster volume is mounted
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted

