---
- name: Configure Web Servers
  hosts: web
  sudo: True
  vars:
    db_host: 172.32.89.41
    db_username: 'WordpressUser'
    db_password: 'W0RDPR355U53R'
    db_name: 'wordpress'
  tasks:
    - name: Install MySQL Client
      apt: package=mysql-client state=installed update_cache=yes cache_valid_time=3600
    - name: check if DB exists
      shell: mysql --host={{ db_host }} --user={{ db_username }} --password={{ db_password }} -e 'SHOW DATABASES;' | grep -c {{ db_name }}
      register: dbstatus
      failed_when: dbstatus.rc == 2
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
